"""adding missing foreign key

Revision ID: eb1fdf5adab0
Revises: 0b631168027c
Create Date: 2025-05-01 00:42:51.704230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb1fdf5adab0'
down_revision: Union[str, None] = '0b631168027c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'task', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'user_id')
    # ### end Alembic commands ###
